version: '3.7'

networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: mapper-nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mapper-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: configs/php
    container_name: mapper-php
    volumes:
      - ../src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - backend

  composer:
    image: composer:latest
    container_name: mapper-composer
    volumes:
      - ../src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - backend

  artisan:
    build:
      context: .
      dockerfile: configs/php
    container_name: mapper-artisan
    volumes:
      - ../src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - backend

  phpmyadmin:
    build: configs/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8081:80"
    depends_on:
      - "mysql"
    networks:
      - backend